// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgNr8lnclUw4JaKKZVCcsqRYvYVdevZRk',
    appId: '1:594144040189:web:4c155fa2af9de4755a1a94',
    messagingSenderId: '594144040189',
    projectId: 'socialapp-3e67f',
    authDomain: 'socialapp-3e67f.firebaseapp.com',
    storageBucket: 'socialapp-3e67f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdbVU69ci3xWl8GOtu3v-Fp0iK-nhelts',
    appId: '1:594144040189:android:1839d535e6c92b8f5a1a94',
    messagingSenderId: '594144040189',
    projectId: 'socialapp-3e67f',
    storageBucket: 'socialapp-3e67f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmsXHxZhwTVwggLKqwfdZ7KRd-VFUsDtM',
    appId: '1:594144040189:ios:66b8a5948f8c1f5c5a1a94',
    messagingSenderId: '594144040189',
    projectId: 'socialapp-3e67f',
    storageBucket: 'socialapp-3e67f.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );
}
